[package]
name = "just-proxy-bin"
version = "0.1.0"
authors = ["skye347 <s347419313@gmail.com>"]
edition = "2018"

[dependencies]
just-proxy-lib = {path = "../just-proxy-lib"}
slog = "2.4.1"
slog-async = "2.3.0"
slog-term = "2.4.0"
structopt = "0.2"
serde_json = "1.0"
serde = "1.0"